[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[project]
name = "atlantisfastapi"
version = "2.1.1"
description = "atlantisfastapi"
readme = "README.md"
authors = [{ name = "Atlantis Labs", email = "r00tail@protonmail.com" }]
dependencies = [
    'coderfastapi ~= 2.3.1'
]

[project.optional-dependencies]
dev = [
    'black ~= 22.10.0'
]

[tool.bumpver]
current_version = "2.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
