[tool.black]
skip-string-normalization = true
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi_exception"
version = "1.0.0"
authors = [
  { name="Dzung Nguyen", email="dung@megatron-solutions.com" },
]
description = "FastAPI Event"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies=[
  'pydantic==2.4.2'
]

[project.urls]
"Homepage" = "https://github.com/megatron-global/fastapi-exception"
"Bug Tracker" = "https://github.com/megatron-global/fastapi-exception/issues"
