[project]
name = "medialoopster"
version = "0.0.21"
description = "medialoopster API wrapper for Python"
readme = "README.md"
license = {text = "MIT"}
authors = [
  {name = "St√©phane Ludwig", email = "stephane.ludwig@swr.de"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests"
]
[project.urls]
homepage = "https://gitlab.com/medialoopster/medialoopster-python"