[tool.poetry]
name = "ipag-core"
version = "0.1.7"
description = ""
authors = ["Sylvain Guieu <sylvain.guieu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25.2"
astropy = "^5.3.2"
pydantic = "^2.3.0"
typing-extensions = "^4.7.1"
class-doc = "^0.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
