[tool.poetry]
name = "revel"
version = "0.7.3"
description = "Effortlessly spice up your terminal apps using colors, progressbars & other goodies"
authors = ["Jakob Pinterits <jakob.pinterits@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
blessed = "^1.19.1"
readchar = "^4.0.3"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
ipykernel = "^6.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip = ".venv"

[tool.isort]
profile = "black"
skip = ".venv"
