[tool.poetry]
authors     = ["9FS <pray4spam@googlemail.com>"]
description = ""
license     = "MIT"
name        = "KFSmedia"
packages    = [{ include = "KFSmedia" }]
readme      = "readme.md"
repository  = "https://github.com/9-FS/2023-09-20-KFSmedia-Library"
version     = "2.0.3"

[tool.poetry.dependencies]
kfsfstr  = "^1.0.0"
kfslog   = "^1.0.0"
pillow   = "^10.0.1"
python   = "^3.11.0"
requests = "^2.31.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core"]
