[project]
name = "h_signature"
version = "0.0.5"
description = "Topological H-signature"
readme = "README.md"

requires-python = ">=3.6"

license = { file = "LICENSE.txt" }

keywords = ["topology", "homology", "robotics"]
authors = [
    { name = "Peter Mitrano", email = "pmitrano@umich.edu" }
]
maintainers = [
    { name = "Peter Mitrano", email = "pmitrano@umich.edu" }
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    # Pick your license as you wish
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    'numpy',
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/UM-ARM-Lab/h_signature"
"Bug Reports" = "https://github.com/UM-ARM-Lab/h_signature/issues"
"Source" = "https://github.com/UM-ARM-Lab/h_signature"

[tool.setuptools]

[build-system]
requires = ["setuptools>=43.0.0", "wheel", "pybind11>=2.4.3"]
build-backend = "setuptools.build_meta"
