[tool.poetry]
name = "python-template"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
black = "23.9.1"
pylint = "2.17.6"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[project]
name = "ooengine"
version = "0.1.1"
authors = [
  { name="Themadpunter", email="themadpunter@noreply.com" },
]
description = "A object-oriented MUD engine"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/familycomicsstudios/ooengine"
"Bug Tracker" = "https://github.com/familycomicsstudios/ooengine/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"