[build-system]
requires = ["hatchling", "wheel"]
build-backend = "hatchling.build"

[project]
name = "simple_notifs"
version = "0.0.3"

authors = [
  { name= "Nico Sanchez", email= "nicosanchez0411@gmail.com"},
]

description = "A python library for creating simple, shortened notification time deltas. This is specifically helpful when time differences like `1h` or `2w` are needed to show a how long something has existed as of right now."

readme = "README.md"

requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "arrow",
]

[project.urls]
"Homepage" = "https://github.com/nicosanc/simple_notifs"
"Bug Tracker" = "https://github.com/nicosanc/simple_notif/issues"