[package]
name = "polars-ffi"
version = "0.33.2"
authors = ["Ritchie Vink <ritchie46@gmail.com>"]
edition = "2021"
homepage = "https://www.pola.rs/"
license = "MIT"
repository = "https://github.com/pola-rs/polars"
description = "FFI utils for the Polars project."
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { path = "../arrow" }
polars-core = { path = "../polars-core" }
